/*
 *
 * This file is automatically generated from Makefile
 */

#ifndef __GXAV_CONFIG_AV_H__
#define __GXAV_CONFIG_AV_H__

#define CONFIG_AV_STC 
#define CONFIG_AV_SDC 
#define CONFIG_AV_VPU 
#define CONFIG_AV_ICAM 
#define CONFIG_AV_DEMUX 
#define CONFIG_AV_VIDEO_OUT 

#endif
